### ISSUE TITLE
Проблема в bind первого поля с Webpack 5

### ISSUE THREAD

**Issue by VictorKrchv** [effector/reflect#10]
Первое поле не бандится https://codesandbox.io/s/affectionate-browser-164yv?file=/src/features/auth/organisms/index.ts - пример. С последующими полями всё работает.

**Comment by sergeysova** [comment]
@VictorKrchv можешь проверить на последних версиях effector/reflect и effector(22) effector-react?

**Comment by AlexandrHoroshih** [comment]
@VictorKrchv 
Проблема должна быть пофикшена в последнем релизе @effector/reflect (версия 7.1.0) 🎉 

Как минимум, репродьюс точно фиксится: https://codesandbox.io/s/sad-dewdney-evncp
