### ISSUE TITLE
Unable use with latest create react app that uses react 18

### ISSUE THREAD

**Issue by vkhv** [effector/reflect#37]
It very appreciate if you update react version
![изображение](https://user-images.githubusercontent.com/6794386/161236183-b62c2cd9-4062-4a8d-a346-0e44ca8aa60f.png)

**Comment by sergeysova** [comment]
I think it is because effector reflect is not updated for react18 yet.

**Comment by AlexandrHoroshih** [comment]
Hi, @vkhv !

React-18 support enabled at https://github.com/effector/reflect/releases/tag/v8.0.0
