### ISSUE TITLE
Reflected components doesn't work properly with Radix UI components with asChild props

### ISSUE THREAD

**Issue by frkam** [effector/reflect#68]
Reproduce:
  - github: https://github.com/frkam/reflect-radix-reproduce
  - codesandbox: https://codesandbox.io/p/github/frkam/reflect-radix-reproduce/main

If you use reflected component as a children for Radix UI component with `asChild` prop you will get this error:
`Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?`

I think the reason for this error is that the reflected components are not wrapped with `forwardRef`

**Comment by sergeysova** [comment]
@frkam Thank you for the report.

Would you like to contribute patch to fix the issue?

**Comment by sergeysova** [comment]
@frkam Fix was released at https://github.com/effector/reflect/releases/tag/v8.3.2.

Would you like to check and close/comment on this issue?

Thank you @kireevmp for the contribution!
